### ISSUE TITLE
第四期

### ISSUE THREAD

**Issue by xuqingfeng** [xuqingfeng/pocket#4]
What are PHP Traits? [链接](http://culttt.com/2014/06/25/php-traits/)

> <small>PHP traits 使用介绍</small>

An 11 line npm package called left-pad with only 10 stars on github was unpublished...it broke some of the most important packages on all of npm. [链接](https://www.reddit.com/r/programming/comments/4bjss2/an_11_line_npm_package_called_leftpad_with_only/)

> <small>npm 水好深 :joy:</small>

bolt - An embedded key/value database for Go. [链接](https://github.com/boltdb/bolt)

> <small>只需一个文件的键值数据库</small>

Migrate to Git from SVN [链接](https://www.atlassian.com/git/tutorials/migrating-overview/)

> <small>使用 Git 替换 SVN</small>

The Art of Programming [video] [链接](https://www.youtube.com/watch?v=C0iFxZ4Caes&index=2&list=PLfUiMmCChhn9JEQW1W1s4V67zKE5-VfnU)

> <small>别人家的 CS 第一课 :+1:</small>

**Comment by ftwbzhao** [comment]
每期收获都很大啊 :smile:
