### ISSUE TITLE
第七期

### ISSUE THREAD

**Issue by xuqingfeng** [xuqingfeng/pocket#7]
phpfmt - php code formatter [链接](https://github.com/phpfmt/fmt)

> 类似 `go fmt` format 代码工具

Android Studio 2.0 | Android Developers Blog [链接](http://android-developers.blogspot.tw/2016/04/android-studio-2-0.html)

> Android Studio 2 发布

Site Reliability Engineering: How Google Runs Production Systems [链接](http://danluu.com/google-sre-book/)

> SRE Goolge 如何保证线上服务稳定

Git commit message 编写指南 [链接](http://www.ruanyifeng.com/blog/2016/01/commit_message_change_log.html)

程序员的自我修养 [链接](https://www.gitbook.com/book/leohxj/a-programmer-prepares/details)

> 用来打发打发时间还是不错的 :smirk:

**Comment by ftwbzhao** [comment]
的确不错 💃 💃
